"""Origins source snapshot imported from anabaptistorigins.org, 2026-10-08."""
import json,re
from pathlib import Path
from html import escape as e
from bs4 import BeautifulSoup
ROOT=Path(__file__).parent
DATA=ROOT/'content/origins'
def build_origins(write):
 eps=json.loads((DATA/'episodes.json').read_text()); photos=json.loads((DATA/'gallery.json').read_text()); places=json.loads((DATA/'locations-enriched.json').read_text())
 (ROOT/'dist/assets/origins/locations.json').write_text(json.dumps(places,ensure_ascii=False))
 def shell(body,active='Overview'):
  tabs=[('Overview',''),('Episodes','episodes/'),('The map','locations/'),('Gallery','gallery/'),('Resources','resources/'),('About the series','about/')]
  return '<link rel="stylesheet" href="/assets/origins/origins.css?v=stories-3"><div class="origins"><div class="wrap origins-nav"><a class="origins-wordmark" href="/origins/">origins<span>An Anabaptist Perspectives series</span></a><nav aria-label="Origins">'+''.join(f'<a {"aria-current=page" if active==n else ""} href="/origins/{p}">{n}</a>' for n,p in tabs)+'</nav></div>'+body+'</div>'
 def cards(items):
  return '<div class="origins-episodes">'+''.join(f'<article class="origin-episode"><a href="/origins/episodes/{x["slug"]}/"><div class="episode-image"><img src="{e(x["image"])}" alt="{e(x["title"])}" loading="lazy"><span class="episode-number">{x["number"]}</span></div><div class="episode-copy"><p class="meta">{x["duration"]} <span>·</span> {x["years"]}</p><h3>{e(x["title"])}</h3><p>{e(x["description"])}</p><span class="origin-link">Watch episode ↗</span></div></a></article>' for x in items)+'</div>'
 def heading(k,t,d):return f'<div class="origins-heading"><p class="eyebrow">{k}</p><h1>{t}</h1><p>{d}</p></div>'
 scenic=photos[7]['image'];hero=f'''<section class="wrap"><div class="origins-hero" style="--scene:url('{scenic}')"><div class="origins-hero-copy"><p class="eyebrow">A ten-part documentary series</p><h1>A different path.<br>A lasting faith.</h1><p>Travel back 500 years to the people and places that shaped the Anabaptist movement.</p><div class="origin-actions"><a class="btn" href="/origins/episodes/{eps[0]['slug']}/">Start watching <span aria-hidden="true">↗</span></a><a class="origin-ghost" href="https://youtu.be/EWVXsq-gUQ4">Watch the trailer</a></div></div><div class="hero-caption">Zürich, Switzerland <span>Where the story begins · 1525</span></div></div><div class="origins-facts"><span><strong>10</strong> episodes in the series</span><span><strong>6</strong> countries visited</span><span><strong>500</strong> years of perspective</span></div></section>'''
 mapcta=f'''<section class="wrap section"><div class="origin-map-teaser"><div><p class="eyebrow">History has a place.</p><h2>Follow the story.<br>Find yourself there.</h2><p>From the streets of Zürich to the moat at Asperen, explore the places behind the convictions.</p><a class="btn" href="/origins/locations/">Explore the interactive map ↗</a><p class="small">{len(places)} mapped locations across six countries</p></div><a href="/origins/locations/" class="map-teaser-art" aria-label="Explore locations"><img src="{e(photos[3]['image'])}" alt="Aerial view of the moat at Asperen" loading="lazy"><span><i aria-hidden="true">●</i> Asperen, Netherlands<br><small>Dirk Willems turned back here.</small></span></a></div></section>'''
 write('/origins/','Anabaptist Origins — Documentary & Interactive Map','Watch Anabaptist Origins and explore the historic locations, photographs and resources behind this documentary series.',shell(hero+f'<section class="wrap section"><div class="origin-section-head"><div><p class="eyebrow">Watch the series</p><h2>Convictions that changed lives.</h2></div><a class="origin-link" href="/origins/episodes/">All episodes ↗</a></div>{cards(eps[:3])}</section>'+mapcta+f'<section class="wrap section origin-photo-callout"><img src="{e(photos[15]["image"])}" alt="Schleitheim Confession" loading="lazy"><div><p class="eyebrow">Look closer</p><h2>The history beyond the screen.</h2><p>Explore manuscripts, places, and objects filmed for the series, and keep studying with the reading list and historical timeline.</p><div class="origin-actions"><a class="btn" href="/origins/gallery/">Open the gallery</a><a class="origin-link" href="/origins/resources/">Study resources ↗</a></div></div></section>'))
 write('/origins/episodes/','Origins Episodes','Watch the published episodes of Anabaptist Origins.',shell('<section class="wrap section">'+heading('The documentary','A story worth returning to.','Six episodes now available from the ten-part Origins series. Begin with Dirk Willems, then follow the movement across Europe.')+cards(eps)+'</section>','Episodes'))
 for x in eps:
  s=BeautifulSoup((DATA/(x['slug']+'.html')).read_text(),'html.parser').select_one('main'); vid=s.select_one('[data-iframe-src]');match=re.search(r'/embed/([\w-]+)',vid.get('data-iframe-src','')) if vid else None
  content=[];started=False
  for tag in s.select('h2,h3,p'):
   text=tag.get_text(' ',strip=True)
   if text=='About This Episode':started=True
   if started and text:
    if text in ['Related Episodes','More Episodes','Explore More']:break
    if tag.name in ['h2','h3']:content.append(f'<h2>{e(text)}</h2>')
    else:content.append('<p>'+e(text)+'</p>')
  player=f'<iframe src="https://www.youtube-nocookie.com/embed/{match[1]}" title="{e(x["title"])}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen loading="lazy"></iframe>' if match else f'<a href="{e(x["source"])}">Watch on the original Origins website</a>'
  body=f'<section class="wrap section">{heading(x["number"]+" · "+x["duration"],e(x["title"]),e(x["description"]))}<div class="origin-player">{player}</div><div class="origin-reading">'+''.join(content)+f'<p><a href="{e(x["source"])}">Original episode & credits ↗</a></p></div></section>'
  write('/origins/episodes/'+x['slug']+'/',x['title']+' — Origins',x['description'],shell(body,'Episodes'))
 gallery='<section class="wrap section">'+heading('The visual archive','Closer to the story.','The manuscripts, places, objects, and faces behind Origins.')+'<div class="origins-gallery">'+''.join(f'<figure><a href="{e(p["full"])}" target="_blank" rel="noopener"><img src="{e(p["image"])}" alt="{e(p["caption"])}" loading="lazy"></a><figcaption>{e(p["caption"])}</figcaption></figure>' for p in photos)+'</div></section>'
 write('/origins/gallery/','Origins Photo Gallery','Explore photographs of the historic places and manuscripts behind Anabaptist Origins.',shell(gallery,'Gallery'))
 for name,title,intro in [('about','The people behind the journey.','A documentary series from Anabaptist Perspectives.'),('resources','Keep exploring.','Read further. Trace the timeline. Take the story with you.')]:
  s=BeautifulSoup((DATA/(name+'.html')).read_text(),'html.parser');parts=[]
  for tag in s.select('h2,h3,h4,p'):
   text=tag.get_text(' ',strip=True)
   if not text or text=='Read More':continue
   parts.append(f'<{tag.name}>{e(text)}</{tag.name}>')
  if name=='resources':parts.insert(0,'<div class="origin-actions"><a class="btn" href="https://anabaptistorigins.org/wp-content/uploads/2026/07/Further_Reading_and_Resources.pdf">Reading list ↗</a><a class="btn outline" href="https://anabaptistorigins.org/wp-content/uploads/2026/07/Master_Timeline.pdf">Full timeline ↗</a></div>')
  else:
   imgs=s.select('img');parts.insert(0,'<div class="origin-team-images">'+''.join(f'<img src="{e(im["src"])}" alt="{e(im.get("alt","Origins presenter"))}" loading="lazy">' for im in imgs[:3])+'</div>')
  write('/origins/'+name+'/',('About Origins' if name=='about' else 'Origins Study Resources'),intro,shell('<section class="wrap section">'+heading('Anabaptist Origins',title,intro)+'<div class="origin-reading">'+''.join(parts)+'</div></section>','About the series' if name=='about' else 'Resources'))
 mapbody='''<section class="wrap origin-atlas"><div class="origin-atlas-heading"><div><p class="eyebrow">The Origins field guide</p><h1>Walk into the story.</h1></div><p>Explore the places where conviction became history.<br>Choose a place to step inside its story.</p></div><div class="atlas-toolbar"><label><span>Find a location</span><input id="place-search" type="search" placeholder="Try Zürich, Dirk Willems, a church…"></label><label><span>Explore by country</span><select id="place-country"><option value="">All six countries</option><option>Austria</option><option>Czechia</option><option>France</option><option>Germany</option><option>Netherlands</option><option>Switzerland</option></select></label><button id="map-reset" class="origin-ghost" type="button">Reset map ↺</button></div><div class="atlas-layout"><aside class="atlas-sidebar" aria-label="Historic locations"><div class="atlas-count" id="place-count" aria-live="polite">46 locations to explore</div><div id="place-list" class="place-list"></div></aside><div class="atlas-map-wrap"><div id="origins-map" aria-label="Map of Anabaptist Origins filming locations"></div><div class="atlas-map-label"><span class="atlas-dot"></span> THE ORIGINS ATLAS <small>Europe · Six countries · One story</small></div></div></div><dialog id="location-story" class="location-story" aria-labelledby="story-title"><button class="story-close" type="button" aria-label="Close location story">✕</button><div id="story-content"></div></dialog><p class="atlas-source">Locations and historical notes from the <a href="https://anabaptistorigins.org/locations/">Origins filming map</a>. The public map currently includes 46 locations from the series’ 65 filming locations.</p><noscript><p>Enable JavaScript to explore the map, or <a href="https://anabaptistorigins.org/locations/">open the original filming map</a>.</p></noscript></section><link rel="stylesheet" href="/assets/origins/leaflet.css"><script defer src="/assets/origins/leaflet.js"></script><script defer src="/assets/origins/map.js?v=stories-3"></script>'''
 write('/origins/locations/','Origins Interactive Map — Historic Anabaptist Locations','Explore 46 historic Anabaptist locations across six European countries, with photographs and notes from the Origins filming team.',shell(mapbody,'The map'))
