import { sqliteTable,text,integer,index } from 'drizzle-orm/sqlite-core';
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),payload:text('payload').notNull(),livePayload:text('live_payload'),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('posts_updated_idx').on(t.updatedAt)]);
export const media=sqliteTable('media',{id:text('id').primaryKey(),filename:text('filename').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()});

// Better Auth's documented core schema. Dates are milliseconds in SQLite.
export const authUser=sqliteTable('auth_user',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),emailVerified:integer('email_verified',{mode:'boolean'}).notNull().default(false),image:text('image'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()});
export const authSession=sqliteTable('auth_session',{id:text('id').primaryKey(),expiresAt:integer('expires_at',{mode:'timestamp_ms'}).notNull(),token:text('token').notNull().unique(),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull(),ipAddress:text('ip_address'),userAgent:text('user_agent'),userId:text('user_id').notNull().references(()=>authUser.id,{onDelete:'cascade'})},t=>[index('auth_session_user_idx').on(t.userId)]);
export const authAccount=sqliteTable('auth_account',{id:text('id').primaryKey(),accountId:text('account_id').notNull(),providerId:text('provider_id').notNull(),userId:text('user_id').notNull().references(()=>authUser.id,{onDelete:'cascade'}),accessToken:text('access_token'),refreshToken:text('refresh_token'),idToken:text('id_token'),accessTokenExpiresAt:integer('access_token_expires_at',{mode:'timestamp_ms'}),refreshTokenExpiresAt:integer('refresh_token_expires_at',{mode:'timestamp_ms'}),scope:text('scope'),password:text('password'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},t=>[index('auth_account_user_idx').on(t.userId)]);
export const authVerification=sqliteTable('auth_verification',{id:text('id').primaryKey(),identifier:text('identifier').notNull(),value:text('value').notNull(),expiresAt:integer('expires_at',{mode:'timestamp_ms'}).notNull(),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},t=>[index('auth_verification_identifier_idx').on(t.identifier)]);
export const studioRecovery=sqliteTable('studio_recovery',{userId:text('user_id').primaryKey().references(()=>authUser.id,{onDelete:'cascade'}),codeHash:text('code_hash').notNull(),updatedAt:integer('updated_at').notNull()});
export const studioSetupUsed=sqliteTable('studio_setup_used',{tokenHash:text('token_hash').primaryKey(),usedAt:integer('used_at').notNull()});
export const studioAuthLimits=sqliteTable('studio_auth_limits',{key:text('key').primaryKey(),bucket:integer('bucket').notNull(),count:integer('count').notNull()});
