import { adminIdentity, authRoute } from './auth.js';
import { publicPage } from './public-content.js';
import { revisionRoute } from './revisions.js';
import { limitRequestBody } from './limited-body.js';
import { validateRichText, renderRichText, richTextPlain, hasRichTextContent } from './rich-text.js';
import assets from './generated-assets.json';
import catalog from './catalog.json';
const initial=new Map(catalog.map(p=>[p.id,p]));
export async function getPublishedPage(env, pathname) {
  return publicPage(await allPosts(env), pathname);
}
const types=['episode','essay','video','resource'];
const prefixes={episode:'episodes',essay:'essays',video:'videos',resource:'resources'};
const MAX=25*1024*1024;
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeURL(value){if(!value)return '';if(/^\/media\/[a-f0-9-]+$/.test(value))return value;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}}
export function youtubeID(v){if(!v)return '';if(/^[\w-]{11}$/.test(v))return v;try{const u=new URL(v);if(['youtube.com','www.youtube.com','youtu.be','www.youtube-nocookie.com'].includes(u.hostname)){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(/^[\w-]{11}$/.test(id))return id;}}catch{}return '';}
export function markdown(s){return String(s||'').split(/\n\s*\n/).map(p=>{let t=esc(p).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');if(t.startsWith('## '))return '<h2>'+t.slice(3)+'</h2>';if(t.startsWith('&gt; '))return '<blockquote>'+t.slice(5)+'</blockquote>';if(t.split('\n').every(l=>l.startsWith('- ')))return '<ul>'+t.split('\n').map(l=>'<li>'+l.slice(2)+'</li>').join('')+'</ul>';return '<p>'+t.replace(/\n/g,'<br>')+'</p>';}).join('');}
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
const html=(v,status=200)=>new Response(v,{status,headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});

function db(env){if(!env.DB)throw new Error('Database unavailable');return env.DB;}
async function textAsset(path){const b=Uint8Array.from(atob(assets[path]),c=>c.charCodeAt(0));return new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).text();}
async function staticResponse(path){let key=path;if(!assets[key])key=path.replace(/\/$/,'')+'/index.html';if(!assets[key])key='/404.html';const ext=key.split('.').pop();const mime={html:'text/html;charset=utf-8',css:'text/css',js:'text/javascript',json:'application/json',svg:'image/svg+xml',png:'image/png',jpg:'image/jpeg',xml:'application/xml',txt:'text/plain'}[ext]||'application/octet-stream';const b=Uint8Array.from(atob(assets[key]),c=>c.charCodeAt(0));return new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip')),{status:key==='/404.html'?404:200,headers:{'content-type':mime,'cache-control':path.startsWith('/admin')?'no-store':'public,max-age=60','x-content-type-options':'nosniff',...(path.startsWith('/admin')?{'referrer-policy':'no-referrer','x-frame-options':'SAMEORIGIN'}:{})}});}
async function rows(env){return (await db(env).prepare('SELECT * FROM posts').all()).results;}
async function allPosts(env,editing=false){const stored=await rows(env);const merged=new Map(catalog.map(p=>[p.id,{...p,version:0,status:'published',hasDraft:false}]));for(const r of stored){const p=editing?JSON.parse(r.payload):r.live_payload?JSON.parse(r.live_payload):null;if(p)merged.set(r.id,{...p,version:r.version,status:r.live_payload?'published':'draft',hasDraft:r.live_payload!==r.payload,updatedAt:r.updated_at});else merged.delete(r.id);}return [...merged.values()].sort((a,b)=>b.date.localeCompare(a.date));}
function validate(input,old){const p={};p.id=old?.id||crypto.randomUUID();p.type=old?.type||input.type;if(!types.includes(p.type))throw new Error('Choose a content type.');for(const k of ['title','excerpt','body','author','alt','number']){p[k]=String(input[k]??(k==='body'?old?.body:'')??'').trim();if(p[k].length>({body:100000,excerpt:1000}[k]||250))throw new Error(k+' is too long.');}if(!p.title)throw new Error('Add a title first.');p.slug=old?.slug||String(input.slug||p.title).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120);if(!p.slug)throw new Error('Add a URL name using letters or numbers.');p.path=old?.path||'/'+prefixes[p.type]+'/'+p.slug+'/';p.date=String(input.date||new Date().toISOString().slice(0,10));if(!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||isNaN(Date.parse(p.date)))throw new Error('Choose a valid date.');p.topics=[...new Set((Array.isArray(input.topics)?input.topics:[]).map(t=>String(t).trim()).filter(Boolean))].slice(0,12);if(p.topics.some(t=>t.length>80))throw new Error('Topic names must be under 80 characters.');p.terms=[...(old?.terms||[])];for(const item of catalog)for(const term of item.terms){const name=term.split('/')[2]?.replace(/-/g,' ');if(name&&p.topics.some(t=>t.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()===name)&&!p.terms.includes(term))p.terms.push(term);}p.premium=old?.premium||false;for(const k of ['image','audio','file','video']){p[k]=safeURL(input[k]);if(input[k]&&!p[k])throw new Error('Use an HTTPS link or uploaded file for '+k+'.');}p.youtube=youtubeID(input.youtube);if(input.youtube&&!p.youtube)throw new Error('Use a valid YouTube video link.');if(input.bodyDoc!=null){p.bodyDoc=validateRichText(input.bodyDoc);p.body=richTextPlain(p.bodyDoc);}else if(old?.bodyDoc&&p.body===old.body){p.bodyDoc=validateRichText(old.bodyDoc);}else if(old?.legacyHtml&&p.body===old.body)p.legacyHtml=old.legacyHtml;return p;}
function card(p){return `<article class="card"><a href="${esc(p.path)}">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.alt||p.title)}" loading="lazy" width="768" height="432">`:''}<div class="meta"><span class="red">${esc(p.type)} ${esc(p.number)}</span><time>${esc(p.date)}</time></div><h3>${esc(p.title)}</h3></a><p>${esc(p.author||p.excerpt.slice(0,145))}</p></article>`;}
async function shell(title,description,body,path,extra=''){let template=await textAsset('/index.html');const before=template.slice(0,template.indexOf('<main id="main">'));const after=template.slice(template.indexOf('</main>')+7);const canonical='https://anabaptistperspectives.org'+path;return before.replace(/<title>.*?<\/title>/,`<title>${esc(title)} | Anabaptist Perspectives</title>`).replace(/<meta name="description"[^>]+>/,`<meta name="description" content="${esc(description.slice(0,165))}">`).replace(/<link rel="canonical"[^>]+>/,`<link rel="canonical" href="${esc(canonical)}">`).replace(/<meta property="og:title"[^>]+>/,`<meta property="og:title" content="${esc(title)}">`).replace(/<meta property="og:description"[^>]+>/,`<meta property="og:description" content="${esc(description.slice(0,165))}">`).replace(/<meta property="og:url"[^>]+>/,`<meta property="og:url" content="${esc(canonical)}">`).replace(/<script type="application\/ld\+json">.*?<\/script>/s,extra)+`<main id="main">${body}</main>`+after;}
async function article(p,preview=false){const body=p.bodyDoc?renderRichText(p.bodyDoc):p.legacyHtml||markdown(p.body);const media=p.youtube?`<iframe class="video" src="https://www.youtube-nocookie.com/embed/${esc(p.youtube)}" title="${esc(p.title)}" allowfullscreen></iframe>`:p.video?`<video controls playsinline preload="metadata" style="width:100%;border-radius:24px"${p.image?` poster="${esc(p.image)}"`:''} src="${esc(p.video)}"></video>`:p.image?`<img style="width:100%;border-radius:28px" src="${esc(p.image)}" alt="${esc(p.alt)}">`:'';const audio=p.audio?(p.audio.startsWith('https://player.captivate.fm/')?`<iframe class="player" src="${esc(p.audio)}" title="Audio player"></iframe>`:`<audio controls style="width:100%" src="${esc(p.audio)}"></audio>`):'';const schema={'@context':'https://schema.org','@type':p.type==='essay'?'Article':'CreativeWork',headline:p.title,description:p.excerpt,datePublished:p.date,author:{'@type':'Person',name:p.author||'Anabaptist Perspectives'},url:'https://anabaptistperspectives.org'+p.path};return shell(p.title,p.excerpt,`<section class="wrap section">${preview?'<p class="eyebrow">Private draft preview · Only administrators can see this</p>':''}<div class="pagehead"><p class="eyebrow">${esc(p.type)} ${esc(p.number)}</p><h1>${esc(p.title)}</h1><p>${esc(p.author)} · ${esc(p.date)}</p><p>${esc(p.excerpt)}</p></div><article class="article">${media}${audio}<div class="prose${p.bodyDoc?' rich-prose':''}">${body}</div>${p.file?`<a class="btn" href="${esc(p.file)}" download>Download resource</a>`:''}<div class="tags">${p.topics.map(t=>`<a href="/library/?topic=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</div></article></section>`,p.path,`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>${preview?'<meta name="robots" content="noindex,nofollow">':''}`);}
async function library(url,posts){const type=Object.entries(prefixes).find(([,v])=>url.pathname==='/'+v+'/')?.[0]||url.searchParams.get('type')||'';const topic=url.searchParams.get('topic')||'';const q=(url.searchParams.get('q')||'').toLowerCase();let list=posts.filter(p=>(!type||p.type===type)&&(!topic||p.topics.includes(topic))&&(!q||[p.title,p.author,p.excerpt,...p.topics].join(' ').toLowerCase().includes(q)));if(/^\/(tag|category)\//.test(url.pathname))list=list.filter(p=>p.terms.includes(url.pathname));const page=Math.max(1,Math.min(Math.ceil(list.length/24)||1,Number(url.searchParams.get('page'))||1));const scope=/^\/(tag|category)\//.test(url.pathname)?url.pathname.split('/')[2].replace(/-/g,' '):'';const heading=topic||scope||({episode:'Watch & listen.',essay:'Read. Reflect. Grow.'}[type]||'The content library.');const options=types.map(t=>`<option value="${t}" ${type===t?'selected':''}>${t[0].toUpperCase()+t.slice(1)}s</option>`).join('');let body=`<section class="wrap section"><div class="pagehead"><p class="eyebrow">The library</p><h1>${esc(heading)}</h1><p>Conversations, essays, and resources to explore.</p></div><form class="filters" action="/library/"><input name="q" value="${esc(url.searchParams.get('q')||'')}" placeholder="Search titles, people, or topics…" aria-label="Search content"><select name="type" aria-label="Content type"><option value="">All content</option>${options}</select>${topic?`<input type="hidden" name="topic" value="${esc(topic)}">`:''}<button class="btn">Search</button></form><p>${list.length} resources</p><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr))">${list.slice((page-1)*24,page*24).map(card).join('')||'<p>No content matches your search. Try another title or topic.</p>'}</div><div class="actions" style="margin-top:32px">`;for(const n of [page-1,page+1])if(n>0&&n<=Math.ceil(list.length/24)){const u=new URL(url);u.searchParams.set('page',n);body+=`<a class="btn outline" href="${esc(u.pathname+u.search)}">${n<page?'Previous':'Next'} page</a>`;}return shell(heading,'Explore Anabaptist Perspectives episodes, essays, videos, and resources.',body+'</div></section>',url.pathname);}
export default {async fetch(req,env){try{return await handle(req,env);}catch(e){console.error('Studio request failed:',new URL(req.url).pathname.startsWith('/api/auth/')?'Authentication unavailable':e.message);return new URL(req.url).pathname.startsWith('/api/')?json({error:'We couldn’t complete that request. Your edits are still here. Please try again.'},503):html('<h1>Temporarily unavailable</h1><p>Please refresh in a moment.</p>',503);}}};
async function handle(req,env){const url=new URL(req.url),path=url.pathname;
if(path.startsWith('/api/auth/'))return authRoute(req,env);
if(path==='/api/public/page') {
  if(req.method!=='GET')return new Response('Method not allowed',{status:405});
  const pathname=url.searchParams.get('path')||'/';
  if(pathname.length>512||!pathname.startsWith('/')||pathname.startsWith('//'))return json({error:'Invalid path'},400);
  return json(await getPublishedPage(env,pathname));
}
if(['/admin/login.css','/admin/login.js'].includes(path))return staticResponse(path);
if(['/admin/setup','/admin/recover','/admin/login'].includes(path))return staticResponse('/admin/login.html');
const identity=(path.startsWith('/admin')||path.startsWith('/api/admin')||path.startsWith('/media/'))?await adminIdentity(req,env):null,isAdmin=!!identity;
if(path.startsWith('/admin')||path.startsWith('/api/admin')){if(!isAdmin){if(path.startsWith('/api/'))return json({error:'Administrator sign-in required.'},401);return staticResponse('/admin/login.html');}
if(req.method!=='GET'&&req.method!=='HEAD'&&req.headers.get('origin')!==url.origin)return json({error:'This request must come from your admin page.'},403);
if(req.method==='POST'&&['/api/admin/posts','/api/admin/media'].includes(path)){
  try{req=await limitRequestBody(req,path.endsWith('/media')?MAX+65536:200000);}catch{return json({error:'This upload or draft is too large.'},413);}
}
if(path.startsWith('/admin/preview/')){const id=path.split('/')[3];const p=(await allPosts(env,true)).find(p=>p.id===id);return p?html(await article(p,true)):json({error:'Draft not found'},404);}
if(path==='/admin'||path==='/admin/')return staticResponse('/admin/index.html');if(path.startsWith('/admin/'))return staticResponse(path);
if(path==='/api/admin/me')return json({email:identity.email});
if(/^\/api\/admin\/posts\/[^/]+\/revisions(?:\/\d+)?$/.test(path))return revisionRoute(req,env,initial);
if(path==='/api/admin/posts'&&req.method==='GET')return json({posts:await allPosts(env,true)});
if(path==='/api/admin/media'&&req.method==='GET')return json({media:(await db(env).prepare('SELECT * FROM media ORDER BY created_at DESC LIMIT 250').all()).results});
if(path==='/api/admin/media'&&req.method==='POST'){if(!env.BUCKET)throw new Error('Storage unavailable');if(Number(req.headers.get('content-length'))>MAX+4096)return json({error:'Please choose a file under 25 MB. Link to YouTube for full videos.'},413);const form=await req.formData(),file=form.get('file');if(!file||typeof file==='string'||!file.size||file.size>MAX)return json({error:'Choose a file between 1 byte and 25 MB.'},400);const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());const first=new TextDecoder().decode(bytes.slice(0,16));let mime='';if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)mime='image/jpeg';else if(bytes[0]===137&&first.slice(1,4)==='PNG')mime='image/png';else if(first.startsWith('RIFF')&&first.slice(8,12)==='WEBP')mime='image/webp';else if(first.startsWith('%PDF-'))mime='application/pdf';else if(first.startsWith('ID3')||(bytes[0]===0xff&&(bytes[1]&0xe0)===0xe0))mime='audio/mpeg';else if(first.startsWith('OggS'))mime='audio/ogg';else if(first.startsWith('RIFF')&&first.slice(8,12)==='WAVE')mime='audio/wav';else if(first.slice(4,8)==='ftyp')mime='video/mp4';if(!mime)return json({error:'Use a JPG, PNG, WebP, PDF, MP3, WAV, OGG, or MP4 file.'},400);const id=crypto.randomUUID(),filename=String(file.name).replace(/[^\w .()-]/g,'').slice(0,180)||'Upload';await env.BUCKET.put(id,file.stream(),{httpMetadata:{contentType:mime}});try{await db(env).prepare('INSERT INTO media (id,filename,mime,size,created_at) VALUES (?,?,?,?,?)').bind(id,filename,mime,file.size,new Date().toISOString()).run();}catch(e){await env.BUCKET.delete(id);throw e;}return json({id,filename,mime,size:file.size,url:'/media/'+id},201);}
if(path==='/api/admin/posts'&&req.method==='POST'){if(Number(req.headers.get('content-length'))>200000)return json({error:'This draft is too large.'},413);const input=await req.json();const action=input.action||'save';if(!['save','publish','unpublish'].includes(action))return json({error:'Unknown action'},400);const id=String(input.id||'');const row=id?await db(env).prepare('SELECT * FROM posts WHERE id=?').bind(id).first():null;const old=row?JSON.parse(row.payload):initial.get(id);if(id&&!old)return json({error:'Content not found.'},404);if(Number(input.version||0)!==(row?.version||0))return json({error:'Someone saved a newer version. Reload the library before editing again.'},409);let p;try{p=validate(input,old);}catch(e){return json({error:e.message},400);}if(action==='publish'&&(!p.excerpt||(!p.body&&!hasRichTextContent(p.bodyDoc)&&!p.youtube&&!p.audio&&!p.file&&!p.video)))return json({error:'Add a short summary and your story, video, audio, or download before publishing.'},400);const all=await allPosts(env,true);if(all.some(x=>x.id!==p.id&&x.path===p.path))return json({error:'That URL is already in use. Choose another URL name.'},409);const payload=JSON.stringify(p);const live=action==='publish'?payload:action==='unpublish'?null:row?row.live_payload:old?JSON.stringify(old):null;const now=new Date().toISOString();let result;if(row)result=await db(env).prepare('UPDATE posts SET payload=?,live_payload=?,version=version+1,updated_at=? WHERE id=? AND version=?').bind(payload,live,now,p.id,row.version).run();else result=await db(env).prepare('INSERT OR IGNORE INTO posts (id,payload,live_payload,version,created_at,updated_at) VALUES (?,?,?,1,?,?)').bind(p.id,payload,live,now,now).run();if(!result.meta.changes)return json({error:'This content changed while you were editing. Reload before saving.'},409);return json({post:{...p,version:(row?.version||0)+1,status:live?'published':'draft',hasDraft:live!==payload,updatedAt:now}});}
return json({error:'Not found'},404);}
if(path.startsWith('/media/')){const id=path.slice(7);if(!/^[a-f0-9-]{36}$/.test(id))return json({error:'Not found'},404);if(!isAdmin){const used=await db(env).prepare("SELECT id FROM posts WHERE live_payload LIKE ? AND COALESCE(json_extract(live_payload, '$.premium'), 0)=0 LIMIT 1").bind('%/media/'+id+'%').first();if(!used)return json({error:'Not found'},404);}const m=await db(env).prepare('SELECT * FROM media WHERE id=?').bind(id).first();const obj=m&&await env.BUCKET.get(id);if(!obj)return json({error:'Not found'},404);return new Response(obj.body,{headers:{'content-type':m.mime,'cache-control':'private,no-store','x-content-type-options':'nosniff','content-disposition':(m.mime==='application/pdf'?'attachment':'inline')+'; filename="'+m.filename.replace(/"/g,'')+'"'}});}
if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method not allowed',{status:405});
if(path.startsWith('/assets/')&&!path.endsWith('/search.json'))return staticResponse(path);
const posts=await allPosts(env);if(path==='/assets/search.json')return json(posts.map(({title,path,excerpt,image,author,number,premium,terms,type,date})=>({title,path,excerpt,image,byline:author,number,premium,terms,kind:type[0].toUpperCase()+type.slice(1),date})));
if(/^\/(episodes|essays)\/page\/\d+\/$/.test(path)){const parts=path.split('/');return Response.redirect(url.origin+'/'+parts[1]+'/?page='+parts[3],302);}
if(path==='/sitemap.xml'){let xml=await textAsset('/sitemap.xml');const hidden=catalog.filter(p=>!posts.some(x=>x.id===p.id)).map(p=>'https://anabaptistperspectives.org'+p.path);xml=xml.replace(/<url>.*?<\/url>/gs,m=>hidden.some(p=>m.includes('<loc>'+esc(p)+'</loc>'))?'':m);const newPaths=posts.filter(p=>!initial.has(p.id)).map(p=>`<url><loc>https://anabaptistperspectives.org${esc(p.path)}</loc></url>`).join('');return new Response(xml.replace('</urlset>',newPaths+'</urlset>'),{headers:{'content-type':'application/xml'}});}
if(path==='/'){let page=await textAsset('/index.html');const eps=posts.filter(p=>p.type==='episode'&&!p.premium),essays=posts.filter(p=>p.type==='essay'&&!p.premium);let i=0;page=page.replace(/<div class="grid">.*?<\/div>(?=<\/section>)/gs,()=>'<div class="grid">'+(i++===0?eps.slice(1,4):essays.slice(0,3)).map(card).join('')+'</div>');const p=eps[0];if(p){const featured=`<article class="feature"><div class="featured-media">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.alt)}">`:''}${p.youtube?`<button class="featured-play" type="button" aria-label="Play ${esc(p.title)}" data-video="${esc(p.youtube)}"><svg width="28" height="28" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5.5v13L19 12Z" fill="currentColor"/></svg></button>`:''}</div><div class="feature-caption"><div class="meta"><span class="red">The latest conversation</span><span>Episode ${esc(p.number)}</span></div><h3><a href="${esc(p.path)}">${esc(p.title)}</a></h3></div></article>`;page=page.replace(/<article class="feature">.*?<\/article>/s,featured);}page=page.replace('<a href="/topics/">Browse topics</a>','<a href="/topics/">Browse topics</a><a href="/library/">All content & resources</a>');return html(page);}
if(['/library/','/episodes/','/essays/','/videos/','/resources/'].includes(path)||/^\/(tag|category)\/[^/]+\/$/.test(path))return html(await library(url,posts));const p=posts.find(p=>p.path===path);const overridden=(await rows(env)).find(r=>JSON.parse(r.payload).path===path);if(overridden){if(!overridden.live_payload)return staticResponse('/404.html');return html(await article(JSON.parse(overridden.live_payload)));}if(p&&!initial.has(p.id))return html(await article(p));return staticResponse(path);
}
